# Generated by Django 3.2.3 on 2021-06-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('ritual', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(choices=[('G', 'good'), ('B', 'bad')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('current_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_habit', to='api.habit')),
                ('new_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_habit', to='api.habit')),
            ],
            options={
                'unique_together': {('user_id', 'current_habit', 'new_habit')},
            },
        ),
    ]
