# Generated by Django 3.2.3 on 2021-06-27 13:18

from django.db import migrations

from django.contrib.auth.models import User

import datetime


def create_super_user(apps, schema_editor):
    User.objects.create_superuser('root', 'admin@habitly.com', 'password', last_login=datetime.datetime.now())


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_super_user),
    ]
