# Generated by Django 3.2.3 on 2021-06-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('user_id', 'title')},
        ),
    ]
