# Generated by Django 3.2.3 on 2021-06-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('first_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_one', to='api.habit')),
                ('second_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_two', to='api.habit')),
            ],
        ),
    ]
