# Generated by Django 3.2.3 on 2021-06-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_intention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intention_habit', to='api.habit'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='current_habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_current_habit', to='api.habit'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='new_habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_new_habit', to='api.habit'),
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetition_habit', to='api.habit')),
            ],
        ),
    ]
