# Generated by Django 3.2.3 on 2021-06-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='user_id',
            field=models.CharField(max_length=32),
        ),
    ]
