# Generated by Django 3.2.3 on 2021-06-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210620_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetition',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
